---
# create certbot cert if SSL certs do not exists yet
- name: Ensure package lists are updated
  apt:
    update_cache: yes

- name: Install Certbot and the Nginx plugin
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Generate SSL certificate
  command: >
    certbot --nginx -d {{ certificate_domain }} --non-interactive --agree-tos --email {{ certificate_email }}
  args:
    creates: /etc/letsencrypt/live/{{ certificate_domain }}/fullchain.pem