node-seeds:                         # List of seed nodes
  - address: "seed-1.chainnet.yago.ninja"
    peer-id: "12D3KooWDzS83A8AXBVBo8pMkFvog1cqgLE2uWfrv57hAuX3bcaQ"
    port: 9100
#  - address: "seed-2.chainnet.yago.ninja"
#    peerID: "peerID-2"
#    port: 8081
#  - address: "seed-3.chainnet.yago.ninja"
#    peerID: "peerID-3"
#    port: 8082
storage-file: "bin/miner-storage"   # File used for persisting the chain status
pub-key:                            # Public key used for receiving mining rewards
  "aSq9DsNNvGhYxYyqA9wd2eduEAZ5AXWgJTbTG7ZBzTqdDQvpbDVh5j5yCpKYU6MVZ35PW9KegkuX1JZDLHdkaTAbKXwfx4Pjy2At82Dda9ujs8d5ReXF22QHk2JA"
mining-interval: "1000s"              # Interval between block creation
p2p-enabled: true                   # Enable or disable network communication
p2p-peer-pub-key: "miner"           # Peer identity (leave empty to generate a random one)
p2p-peer-port: 9100                 # Port used for network communication with other peers
p2p-min-conn: 5                     # Minimum number of connections
p2p-max-conn: 100                   # Maximum number of connections
p2p-conn-timeout: "60s"             # Maximum duration of a connection
p2p-write-timeout: "20s"            # Maximum duration of a write stream
p2p-read-timeout: "20s"             # Maximum duration of a read stream
p2p-buffer-size: 4096               # Read buffer over the network
