[tools]
go = "1.26.2"
goreleaser = "2.15.4"
golangci-lint = "2.11.4"
oapi-codegen = "2.6.0"
protoc = "23.4"
protoc-gen-go = "1.36.11"
protoc-gen-go-grpc = "1.80.0"
"go:golang.org/x/tools/cmd/goimports" = "v0.38.0"
"go:github.com/go-delve/delve/cmd/dlv" = "v1.26.3"
