---
- name: Download Prometheus binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus binary
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Move Prometheus binaries
  command: mv /opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin/

- name: Move Prometheus related files
  copy:
    src: /opt/prometheus-{{ prometheus_version }}.linux-amd64/
    dest: /etc/prometheus/
    remote_src: yes

- name: Provide Prometheus configuration
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'

- name: Create Prometheus systemd service file
  template:
    src: files/prom.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Start Prometheus service
  systemd:
    name: prometheus
    enabled: true
    state: started
