---
- name: Configure Grafana data source
  template:
    src: files/prometheus-source.yaml
    dest: /etc/grafana/provisioning/datasources/prometheus-source.yaml

- name: Ensure the provisioning directory exists
  file:
    path: /etc/grafana/provisioning/dashboards/custom
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Ensure the provisioning directory for list charts exists
  file:
    path: /etc/grafana/provisioning/dashboards/list
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'

- name: Copy the dashboard provisioning YAML
  copy:
    src: files/dashboard_provision_monitoring.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard_provision_monitoring.yml
    owner: grafana
    group: grafana
    mode: '0644'

- name: Copy the dashboard provisioning YAML for chart list
  copy:
    src: files/dashboard_provision_monitoring.yml
    dest: /etc/grafana/provisioning/dashboards/dashboard_provision_list.yml
    owner: grafana
    group: grafana
    mode: '0644'

- name: Copy all dashboard provisioning YAML files
  copy:
    src: "{{ item }}"
    dest: /etc/grafana/provisioning/dashboards/custom
    owner: grafana
    group: grafana
    mode: '0644'
  with_fileglob:
    - files/dashboards/*.json

- name: Copy the list of dashboard JSON files
  copy:
    src: files/dashboard-list.json
    dest: /etc/grafana/provisioning/dashboards/list
    owner: grafana
    group: grafana
    mode: '0644'

- name: Restart Grafana service
  systemd:
    name: grafana-server
    state: restarted