---
# Install dependencies
- name: Install prerequisites
  apt:
    name:
      - wget
      - curl
      - gnupg
      - apt-transport-https
      - software-properties-common
      - nginx
    state: present
    update_cache: yes

# Install and configure Prometheus
- name: Install and configure Prometheus
  block:
    - name: Download Prometheus binary
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus binary
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Prometheus binaries
      command: mv /opt/prometheus-2.47.0.linux-amd64/prometheus /usr/local/bin/

    - name: Move Prometheus related files
      copy:
        src: /opt/prometheus-2.47.0.linux-amd64/
        dest: /etc/prometheus/
        remote_src: yes

    - name: Provide Prometheus configuration
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: '0644'

    - name: Create Prometheus systemd service file
      template:
        src: files/prom.service
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'

    - name: Start Prometheus service
      systemd:
        name: prometheus
        enabled: true
        state: started

# Install Grafana
- name: Install and configure Grafana
  block:
    - name: Add Grafana GPG key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: /etc/apt/trusted.gpg.d/grafana.asc
      become: true

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Configure Grafana service
      template:
        src: templates/grafana.ini.j2
        dest: /etc/grafana/grafana.ini

    - name: Configure Grafana data source
      template:
        src: templates/data-source.yaml.j2
        dest: /etc/grafana/provisioning/datasources/data-source.yaml

    - name: Start Grafana service
      systemd:
        name: grafana-server
        enabled: true
        state: started

# Install and configure Nginx
- name: Install and configure Nginx
  block:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        enabled: true
        state: started

    - name: Deploy Nginx configuration for Grafana
      template:
        src: templates/dashboard-nginx.j2
        dest: /etc/nginx/sites-available/dashboard
      notify: Reload Nginx

    - name: Enable the dashboard site
      file:
        src: /etc/nginx/sites-available/dashboard
        dest: /etc/nginx/sites-enabled/dashboard
        state: link
        force: yes


