apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chainnet-node
  labels:
    app: chainnet
spec:
  serviceName: "chainnet-node"
  replicas: 1
  selector:
    matchLabels:
      app: chainnet-node
  template:
    metadata:
      labels:
        app: chainnet-node
    spec:
      containers:
        - name: chainnet-node
          image: "{{ .Values.imageNode.repository }}:{{ .Values.imageNode.tag }}"
          imagePullPolicy: "{{ .Values.imageNode.pullPolicy }}"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: chainnet-node-storage
              mountPath: /data
            - name: config-volume
              mountPath: /etc/config.yaml
              subPath: config.yaml
          env:
            - name: CONFIG_FILE
              value: /etc/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: chainnet-node-storage
          persistentVolumeClaim:
            claimName: chainnet-node-pvc
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
            items:
                - key: config.yaml
                  path: config.yaml
