---
- name: Deploy Chainnet blockchain on the network
  hosts: nodes
  become: true  # Use sudo privileges
  become_method: sudo
  vars:
    app_dir: /var/chainnet
    config: 'default-config.yaml'
    repo_url: 'https://github.com/yago-123/chainnet.git'
    branch: 'add-grafana-monitoring'
    go_version: '1.23.0'
    go_tar: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    go_code: /usr/local
    go_bin_path: "{{ go_code }}/go/bin"
    target: "{{ node }}"
  roles:
    - blockchain
