---
- name: Deploy Chainnet blockchain on the network
  hosts: all
  become: true  # Use sudo privileges
  become_method: sudo
  vars:
    app_dir: /var/chainnet
    config: 'default-config.yaml'
    repo_url: 'https://github.com/yago-123/chainnet.git'
    branch: 'master'
    go_version: '1.23.0'
    target: "{{ node }}"
  roles:
    - blockchain
