---
- name: Setup Chainnet monitoring
  hosts: all
  become: true
  become_method: sudo
  vars:
    prometheus_version: '2.47.0'
    domain: 'dashboard.chainnet.yago.ninja'
  tasks:
    - name: Check if Grafana is running
      import_tasks: check_grafana.yml

    - name: Install and start Grafana if not running
      include_role:
        name: visualization
      when: grafana_installed

    - name: Set up monitoring
      include_role:
        name: monitoring
