server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/log/chainnet/*log
    pipeline_stages:
      - regex:
          expression: 'time="(?P<timestamp>[^"]+)" level=(?P<level>[a-zA-Z]+) msg="(?P<message>.*)"'
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
      - labels:
          level:
      - output:
          source: message
