server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/chainnet/*log

    pipeline_stages:
      - regex:
          expression: 'time="(?P<time>[^"]+)" level=(?P<level>\w+) msg="(?P<msg>[^"]+)"'
      - labels:
          time: time
          level: level
      - json:
          expressions:
            tx_hash: msg
            block_hash: msg
            block_height: msg
            tx_count: msg
            nonce: msg
      - drop:
          expression: 'msg=".*"'
