{
 "title": "02 - Blocks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_height", "legendFormat": "height" }
   ]
  },
  {
   "title": "Circualting Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_circulating_supply", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Circulating Supply Increase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(chain_circulating_supply[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_last_block_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Txs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_last_block_txs", "legendFormat": "num txs" }
   ]
  },
  {
   "title": "Header Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_last_block_header_size", "legendFormat": "Header Size" }
   ]
  },
  {
   "title": "Inputs Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_last_block_inputs_size", "legendFormat": "Inputs Size" }
   ]
  },
  {
   "title": "Outputs Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_last_block_outputs_size", "legendFormat": "Outputs Size" }
   ]
  },
  {
   "title": "Last Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "chain_last_block_size", "legendFormat": "block size" },
    { "expr": "chain_last_block_txs", "legendFormat": "num txs" }
   ]
  },
  {
   "title": "Last Block Size Parts",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "chain_last_block_inputs_size", "legendFormat": "inputs size" },
    { "expr": "chain_last_block_outputs_size", "legendFormat": "outputs size" },
    { "expr": "chain_last_block_header_size", "legendFormat": "header size" }
   ]
  },
  {
   "title": "Last Block Number Inputs vs. Outputs %",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / ($A+$B))*100", "type": "math" },
    { "expression": "($B / ($A+$B))*100", "type": "math" }
   ]
  },
  {
   "title": "Circulating Supply ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "chain_circulating_supply", "legendFormat": "supply" }
   ]
  }
 ]
}