{
 "title": "07 - LibP2P",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Bandwidth ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Bandwidth Incoming ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bandwidth_total_incoming_bytes", "legendFormat": "in" }
   ]
  },
  {
   "title": "Bandwidth Outgoing ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bandwidth_total_outgoing_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Total Event Subscribers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (libp2p_eventbus_subscriber_event_queued)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Emitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (libp2p_eventbus_events_emitted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Conns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Opened Conns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_swarm_connections_opened_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed Conns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_swarm_connections_closed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Emitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "libp2p_eventbus_events_emitted_total",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Queue Length Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscriber_queue_length",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  },
  {
   "title": "Bandwidth Rate ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "bandwidth_rate_incoming_bytes", "legendFormat": "in" },
    { "expr": "bandwidth_rate_outgoing_bytes", "legendFormat": "out" }
   ]
  },
  {
   "title": "Bandwidth Peer Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bandwidth_total_bytes_by_peer{operation=\"in\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Swarm Conns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "libp2p_swarm_connections_opened_total",
     "legendFormat": "opened"
    },
    {
     "expr": "libp2p_swarm_connections_closed_total",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "Events Emitted Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_eventbus_events_emitted_total",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "95th Percentile Swarm Conn Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(libp2p_swarm_connection_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Top 5% Conn Duration"
    }
   ]
  },
  {
   "title": "Bandwidth Protocol Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol) (bandwidth_total_bytes_by_protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  }
 ]
}