- name: Deploy application from Git
  hosts: nodes
  become: yes
  become_method: sudo

  vars:
    app_dir: /var/chainnet
    repo_url: 'https://github.com/yago-123/chainnet.git'
    branch: 'master'
    go_version: '1.23.0'
    go_tar: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    go_bin_path: /usr/local/go/bin

  tasks:
    - name: Ensure apt is up to date and install necessary packages
      apt:
        update_cache: yes
        name:
          - make
          - protobuf-compiler
        state: present
      tags:
        - update
        - packages

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
      tags:
        - directory

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes
        update: yes
      tags:
        - git

    - name: Download and install Go binary
      block:
        - name: Download Go binary
          get_url:
            url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
            dest: "{{ go_tar }}"

        - name: Extract Go binary
          unarchive:
            src: "{{ go_tar }}"
            dest: "/usr/local"
            remote_src: yes
      tags:
        - go

    - name: Install Go tools
      block:
        - name: Install protoc-gen-go
          shell: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          environment:
            PATH: "{{ go_bin_path }}:{{ ansible_env.PATH }}"

        - name: Install protoc-gen-go-grpc
          shell: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          environment:
            PATH: "{{ go_bin_path }}:{{ ansible_env.PATH }}"
      tags:
        - go-tools

    - name: Build the application with make
      shell: make node
      args:
        chdir: "{{ app_dir }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ go_bin_path }}:/usr/bin:{{ ansible_env.HOME }}/go/bin"
      tags:
        - build
