{
 "title": "Mempool",
 "time": { "from": "2025-01-18T17:56:19.979Z", "to": "2025-01-18T18:23:02.098Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number Txs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_num_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_txs_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_total_fee", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_storage_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Channoshis Per Byte",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B / $A)*100000000", "type": "math" }
   ]
  },
  {
   "title": "Avg Fee Per Tx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "mempool_num_txs", "legendFormat": "num transactions" },
    { "expr": "mempool_txs_balance", "legendFormat": "volume" },
    { "expr": "mempool_total_fee", "legendFormat": "fees volume" }
   ]
  },
  {
   "title": "Inputs vs. Outputs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "mempool_num_inputs", "legendFormat": "inputs" },
    { "expr": "mempool_num_outputs", "legendFormat": "outputs" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mempool_storage_size", "legendFormat": "mempool size" },
    { "expr": "mempool_num_txs", "legendFormat": "num transactions" },
    { "expression": "($C / $A)*100000000", "type": "math" }
   ]
  }
 ]
}