{
 "title": "UTXO Set",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "UTXO Output Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "utxo_set_output_balance", "legendFormat": "output balance" }
   ]
  },
  {
   "title": "UTXO Outputs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "utxo_set_num_outputs", "legendFormat": "num outputs" }
   ]
  },
  {
   "title": "UTXO Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "utxo_set_storage_size", "legendFormat": "size" }
   ]
  }
 ]
}