{
 "title": "Validator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Blocks Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Blocks Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heavy_validator_block_total_rejected",
     "legendFormat": "blocks rejected"
    }
   ]
  },
  {
   "title": "Transactions Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Transactions Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heavy_validator_tx_total_rejected",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Headers Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Headers Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heavy_validator_header_total_rejected",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Blocks Accepted vs. Rejected",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expression": "$A - $B", "type": "math" },
    {
     "expr": "round(increase(heavy_validator_block_total_rejected[$__rate_interval]), 1)",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Transactions Accepted vs. Rejected",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "round(increase(heavy_validator_tx_total_rejected[$__rate_interval]), 1)",
     "legendFormat": "rejected"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Headers Accepted vs. Rejected",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "round(rate(heavy_validator_header_total_rejected[$__rate_interval]), 1)",
     "legendFormat": "rejected"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  }
 ]
}