{
 "title": "Golang Runtime",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "allocated" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "in use" },
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "allocated " }
   ]
  },
  {
   "title": "Stack Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "in use" },
    { "expr": "go_memstats_stack_sys_bytes", "legendFormat": "allocated" }
   ]
  },
  {
   "title": "Span Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_mspan_inuse_bytes", "legendFormat": "in use" },
    { "expr": "go_memstats_mspan_sys_bytes", "legendFormat": "allocated" }
   ]
  },
  {
   "title": "Mcache Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_mcache_inuse_bytes", "legendFormat": "in use" },
    { "expr": "go_memstats_mcache_sys_bytes", "legendFormat": "allocated" }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" },
    {
     "expr": "increase(go_gc_duration_seconds_count[$__rate_interval])",
     "legendFormat": "gc cycles"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "num goroutines" }
   ]
  },
  {
   "title": "Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  }
 ]
}