{
 "title": "metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blocks Mined",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blockchain_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UTXOs Inputs Tracked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_inputs_tracked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Mempool Fees",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_total_fee", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks Mined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    { "expr": "blockchain_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "mempool_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Fees",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "targets": [
    { "expr": "mempool_total_fee", "legendFormat": "__auto" }
   ]
  }
 ]
}