name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.59.1'

      - name: Build CLI
        run: make cli

      - name: Build Node
        run: make node

      - name: Build Miner
        run: make miner

      - name: Build NESPV
        run: make nespv

      - name: Test code
        run: make test
