name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mise tools
        uses: jdx/mise-action@v3
        with:
          install: true

      - name: Generate protobuf files
        run: make protobuf

      - name: Run golangci-lint
        run: make lint

      - name: Build Node
        run: make node

      - name: Build Miner
        run: make miner

      - name: Build NESPV
        run: make nespv
      
      - name: Build CLI
        run: make cli

      - name: Test code
        run: make test
