# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build CLI
      run: make chainnet-cli

    - name: Build Node
      run: make chainnet-node

    - name: Test code
      run: make test

  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5